"""added column appointment_name to appointment table

Revision ID: 38d8fd2ddc91
Revises: 726e2126fe1f
Create Date: 2025-05-31 03:11:27.683248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d8fd2ddc91'
down_revision: Union[str, None] = '726e2126fe1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_name', sa.String(), nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'doctors', ['patient_id'], ['id'])
    op.drop_column('appointments', 'appointment_name')
    # ### end Alembic commands ###
